### PR TITLE
[iOS] Fix compiler warnings.

### PR DESCRIPTION
**Pull request by e2l3n**
<b>Description</b>:
- Add `.DS_Store` to `.gitignore`.
- Set `CLANG_ENABLE_MODULES` to `NO` in order to resolve compiler warnings of type `warning: Could not resolve external type c:objc(cs)`.
- Rebuild Zip.framework binary with `CLANG_ENABLE_MODULES=NO`.

<b>TeamPulse</b>: Closely related to [[LiveSync][iOS] Cannot build iOS with livesync plugin](http://teampulse.telerik.com/view#item/310252).

### CODE REVIEW

**Comment by e2l3n** [comment]
ping @galexandrov @mbektchiev @Mitko-Kerezov

**Comment by mbektchiev** [comment]
Can you check that these parameters are as described in [this forum thread](https://forums.developer.apple.com/thread/17921#66135): 
- Precompile Prefix (GCC_PRECOMPILE_PREFIX_HEADER) = NO
- Debug Information Format (DEBUG_INFORMATION_FORMAT) = DWARF with dSYM
- Enabled Modules (C and Objective-C) (CLANG_ENABLE_MODULES) = NO

**Comment by mbektchiev** [comment]
:+1:

**Comment by e2l3n** [comment]
Build settings have been changed to 

```
CLANG_MODULES_AUTOLINK=NO
DEBUG_INFORMATION_FORMAT="dwarf-with-dsym";
CLANG_ENABLE_MODULES = NO;
GCC_PRECOMPILE_PREFIX_HEADER = NO;
CLANG_ENABLE_MODULE_DEBUGGING=YES;
```

**Pull request merged**
